name: MPP Dev Deployment

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
          with:
            node-version: 19.x

      - name: Run yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run yarn build:dev
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Upload to server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_path: /var/www/dev/
          path: client/
